import classNames from "classnames";
import { useAtom, atom } from "jotai";
import { useAtomValue, useUpdateAtom } from "jotai/utils";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useMemo, useState } from "react";
import styles from "../styles/Home.module.css";

var Pokedex = require('pokedex'),
    pokedex = new Pokedex();

export const selectedPokemonAtom = atom<string | number | null>(null);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PokemonPicker />
      <PokemonShower />
    </div>
  );
};

const PokemonPicker = () => {
  // const [searchText, setSearchText] = useState('');
  const [selectedPokemon, setSelectedPokemon] = useAtom(selectedPokemonAtom);

  return (
    <div>
      <input
        value={selectedPokemon?.toString()}
        placeholder={"Choose your Pokemon"}
        onChange={(e) => setSelectedPokemon(e.target.value)}
        className={'bg-red-400/50 rounded-md text-white p-5'}
      />
    </div>
  );
};

const PokemonShower = () => {
  const selectedPokemon = useAtomValue(selectedPokemonAtom);
  const hydratedPokemon: any|any[] = useMemo(() => pokedex.pokemon(selectedPokemon), [selectedPokemon]);

  if (!hydratedPokemon || !hydratedPokemon.sprites || Array.isArray(hydratedPokemon)) {
    return <div>Choose only one</div>;
  }

  return <div><img src={hydratedPokemon.sprites.animated}/></div>;
};

export default Home;
